# Generated by Django 2.2 on 2021-09-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20210908_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.BooleanField(choices=[('T', 'Transgender'), ('M', 'Male'), ('F', 'Female')]),
        ),
    ]
