# Generated by Django 2.2 on 2021-09-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210908_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_staff',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('T', 'Transgender'), ('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
