# Generated by Django 2.2 on 2021-09-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20210908_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
